### ISSUE TITLE
NextJS - Cannot read properties of undefined (reading 'transactionbuilderconfigbuilder_new')

### ISSUE THREAD

**Issue by bigirishlion** [spacebudz/lucid#174]
tsconfig.json
```javascript
{
    "compilerOptions": {
        "target": "ES2020",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    "exclude": ["node_modules"]
}
```
next.config.js
```javascript 
const nextConfig = {
    reactStrictMode: true,
    swcMinify: true,
    webpack: (config) => {
        config.experiments = {
            asyncWebAssembly: true,
            topLevelAwait: true,
            layers: true // optional, with some bundlers/frameworks it doesn't work without
        };

        return config;
    }
};

module.exports = nextConfig;
```

Lucid Version
`"lucid-cardano": "^0.9.6",`

**Comment by alessandrokonrad** [comment]
Could you try out Lucid `0.9.8` and lemme know if it works with this version?

**Comment by VladislavTonev** [comment]
@alessandrokonrad Greetings! I receive the same error, using Chrome v113, node v18.16.0 Vue3 and lucid version 0.10.2. I also installed wasm-loader v1.3.0., unfortunatelly with no result.  I've tried different versions of lucid, the error remains. Can it be a problem with configuration? I am open for discussion in discord if needed. Thank you in advance!

**Comment by mPaella** [comment]
Getting this as well on `0.10.4`

```
TypeError: Cannot read properties of null (reading 'TransactionBuilderConfigBuilder')
    at Function.new (webpack-internal:///(api)/./node_modules/lucid-cardano/esm/src/lucid/lucid.js:77:81)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BackOff.eval [as request] (webpack-internal:///(api)/./utils/cardano/LucidWrapper.ts:41:100)
```

```
webpack: (config, options) => {
        config.experiments = {
            ...config.experiments,
            asyncWebAssembly: true,
            layers: true,
            topLevelAwait: true,
        };

        config.resolve.fallback = {
            ...config.resolve.fallback,
            fs: false,
            os: false,
            path: false,
            crypto: false,
            process: require.resolve("process/browser"),
        };
        return config;
    },
```

**Comment by VladislavTonev** [comment]
Download one of these templates: https://meshjs.dev/starter-templates and use it as a starting point. I believe the setup works with lucid, because both libs use cardano serialization lib.

**Comment by Emmanuel-FSE** [comment]
I am getting the same error with angular, any solution will be much appreciated.

**Comment by hgextracts** [comment]
any updates on this also having same issue next js 13.4 and lucid 10.6

**Comment by nnamdiarimah** [comment]
I'm running into this issue in angular as well.

**Comment by Varagos** [comment]
Running into this issue as well with React when using webpack for bundling

**Comment by thaddeusdiamond** [comment]
Opened https://github.com/spacebudz/lucid/pull/220 which might provide a fix.  Seems to be an issue with middleware usage of lucid specifically.

**Comment by thaddeusdiamond** [comment]
I pushed a Pull Request (#220) for this and published it to this npm module: https://www.npmjs.com/package/lucid-cardano-nextjs

**Comment by openVietAnh** [comment]
Why this is still not fixed? I'm also having this errorWhy this is still not fixed? I'm also having this error
